clc;

PATH_LOSS_EXPONENT = 4.7;
SHADOWING_STANDARD_DEVIATION = 8;
MODULATION = 3;
ENCODING = 3;
PREAMBLE_LENGTH = 2;
FRAME_LENGTH = 50;
NUMBER_OF_NODES = 25; 
TERRAIN_DIMENSIONS_X = 25.0; 
TERRAIN_DIMENSIONS_Y = 25.0;
TOPOLOGY = 2; 
GRID_UNIT = 3.0;

TEMPORAL_CORRELATION_COEFFICIENT = 0.5;
SPATIAL_CORRELATION_COEFFICIENT = 0.5;